BookStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("orders/", include('orders.urls')),
                  path("products/", include('products.urls')),
                  path("", include('users.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path("", views.CartDetails.as_view(), name='cart_detail'),
    path('create', views.CreateOrder.as_view(), name='order'),
    path('thanks', views.OrderCompleted.as_view(), name='complete'),
    path("add/<book_id>", views.CartAddItem.as_view(), name='cart_add'),
    path("remove/<int:product_id>", views.RemoveProductFromCart.as_view(), name='cart_remove'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path("books/", views.BookListView.as_view(), name='books'),
    path("<category_slug>", views.BookListByCategory.as_view(), name='book-list'),
    path("books/search", views.SearchBook.as_view(), name='search_book'),

]

users/urls.py
from django.urls import path, include

from . import views

app_name = ''

urlpatterns = [
    path('index/', views.MainPage.as_view(), name='home'),
    path("", views.MainPage.as_view()),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('users/', include('django.contrib.auth.urls')),

]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Count
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from orders.models import OrderItem
from orders.services import Cart
from products.models import Book, Category


class MainPage(TemplateView):
    template_name = 'user/index.html'
    book = Book.objects.none()
    categories = Category.objects.all()
    try:
        orders = OrderItem.objects.values('product').annotate(count=Count('quantity')).order_by('-count')
        for order in orders:
            print (orders)
            books = Book.objects.all().filter(id=order['product'])
            book |= books
    finally:
        pass

    def get_context_data(self, **kwargs):
        context = super(MainPage, self).get_context_data()
        cart = Cart(self.request)
        total_price = cart.get_total_price()
        total_items = cart.__len__()
        context['books'] = self.book
        context['categories'] = self.categories
        context['total_items'] = total_items
        context['total_price'] = total_price
        return context


class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

users/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap3 %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Book Store </title>

 		<!-- Google font -->
 		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

 		<!-- Bootstrap -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}"/>

 		<!-- Slick -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css'%}"/>
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css'%}"/>

 		<!-- nouislider -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css'%}"/>

 		<!-- Font Awesome Icon -->
 		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">

 		<!-- Custom stlylesheet -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css'%}"/>

 		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
 		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
 		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
 		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    </head>
    {% include 'navbar.html' %}

	<body>

    {% block content %}


    {% endblock %}


    {% include 'footer.html' %}

	</body>
</html>

users/templates/footer.html
{% load staticfiles %}

    <footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-5">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Orders and Returns</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="#">My Account</a></li>
									<li><a href="#">View Cart</a></li>
									<li><a href="#">Wishlist</a></li>
									<li><a href="#">Track My Order</a></li>
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>


						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}" ></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>

users/templates/navbar.html
{% load staticfiles %}

<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
						<li><a href="#"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
					</ul>
					<ul class="header-links pull-right">
						<li><a href="#">{{total_price}} </a><i class="fa fa-dollar"></i></li>
						{% if user.is_authenticated %}
							<li style="font-size:16px; color:red">Hi {{ user.username }}!</li>
							<li><a href="{% url 'logout'%}">logout</a></li>
						{% else %}
							<li><a href="{% url 'login'%}"><i class="fa fa-user-o"></i> My Account</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="#" class="logo">
									<img src="{% static 'img/logo.png'%}" alt="">
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form action="{% url 'products:search_book' %}" method="POST">
									{%csrf_token%}
								<input style="width: calc(100% - 260px);margin-right: -4px;" class="input search" name="book-search" placeholder="Search here" type="text">
								<input class="search-btn" type="submit" value="search">
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">

								<!-- Cart -->
								<div class="dropdown">
									<a href="{% url 'orders:cart_detail' %}">
										<i class="fa fa-shopping-cart"></i>
										<span>Your Cart</span>
										<div class="qty">{{total_items}}</div>
									</a>
								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="active"><a href="{% url 'home'%}">Home</a></li>
						<li><a href="{%url 'products:books'%}">Categories</a></li>
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->