BookStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("orders/", include('orders.urls')),
                  path("products/", include('products.urls')),
                  path("", include('users.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path("", views.CartDetails.as_view(), name='cart_detail'),
    path('create', views.CreateOrder.as_view(), name='order'),
    path('thanks', views.OrderCompleted.as_view(), name='complete'),
    path("add/<book_id>", views.CartAddItem.as_view(), name='cart_add'),
    path("remove/<int:product_id>", views.RemoveProductFromCart.as_view(), name='cart_remove'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path("books/", views.BookListView.as_view(), name='books'),
    path("<category_slug>", views.BookListByCategory.as_view(), name='book-list'),
    path("books/search", views.SearchBook.as_view(), name='search_book'),

]

users/urls.py
from django.urls import path, include

from . import views

app_name = ''

urlpatterns = [
    path('index/', views.MainPage.as_view(), name='home'),
    path("", views.MainPage.as_view()),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('users/', include('django.contrib.auth.urls')),

]

orders/models.py
from django.contrib.auth.models import User
from django.db import models
from products.models import Book


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, )
    address = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Book, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms

from .models import Order

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 5)]


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['email', 'address']


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView
from products.models import Book

from .forms import OrderCreateForm, CartAddProductForm
from .models import OrderItem, Order
from .services import Cart


@method_decorator(login_required, name='dispatch')
class CreateOrder(TemplateView):
    template_name = 'order.html'

    def post(self, request):
        cart = Cart(request)
        order = Order.objects.none()
        form = OrderCreateForm(request.POST)
        user = request.user
        if form.is_valid():
            cd = form.cleaned_data
            order = Order.objects.create(
                user=user,
                email=cd['email'],
                address=cd['address']
            )
            order.save()
            for item in cart:
                q_book = (Book.objects.filter(id=item['book_id']))

                OrderItem.objects.create(
                    order=order,
                    product=q_book[0],
                    price=item['price'],
                    quantity=item['quantity']
                )
            cart.clear()
        return HttpResponseRedirect('/orders/thanks', {'order': order})

    def get_context_data(self, *args):
        context = super(CreateOrder, self).get_context_data()
        form = OrderCreateForm()
        cart = Cart(self.request)
        total_items = cart.__len__()
        total_price = cart.get_total_price()
        context['cart'] = cart
        context['form'] = form
        context['total_items'] = total_items
        context['total_price'] = total_price
        print(total_items, total_price)
        return context


class OrderCompleted(TemplateView):
    template_name = 'thanks.html'

    def get_context_data(self, **kwargs):
        context = super(OrderCompleted, self).get_context_data()
        context['order'] = Order.objects.latest('id')
        return context


@method_decorator(require_POST, name='dispatch')
class CartAddItem(TemplateView):
    def post(self, request, book_id, *args, **kwargs):
        cart = Cart(request)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(book_id, quantity=cd['quantity'], update_quantity=cd['update'])
        return HttpResponseRedirect('/orders/')


class CartDetails(TemplateView):
    template_name = 'cart_detail.html'

    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        context = {'cart': cart}
        return self.render_to_response(context)


class RemoveProductFromCart(TemplateView):
    template_name = 'cart_detail.html'

    def get(self, request, product_id, **kwargs):
        cart = Cart(request)
        product = get_object_or_404(Book, id=product_id)
        print(product)
        cart.remove(product)
        return HttpResponseRedirect('/orders/')

orders/templates/cart_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart</h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #D10024">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with book=item.book  %}
                        <tr>
                            <td>
                                <a href="{{ book.get__absolute_url }}">
                                    <img src="{% if book.image %} {{ book.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ book.name }}</td>
                            <td>
                                <form action="{% url 'orders:cart_add' book.id %}" method="post">

                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url 'orders:cart_remove' book.id %}" class="btn btn-danger">Remove</a>
                            </td>

                            <td> {{ book.price }}</td>
                            <td> {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #D10024">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>Price {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
            <form method="POST" >
            <p class="text-right">
                <a href="{% url 'products:books' %}" class="btn btn-default">Continue Shopping</a>
                <a href="{% url 'orders:order' %}" class="btn btn-primary">Checkout</a>
            </p>
            </form>
        </div>
    </div>


{% endblock %}

orders/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8">
                <h4 class="page-header">Checkout</h4>
                <form action="{% url 'orders:order' %}" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}<br>

                    <input type="hidden" name="user" value="{{ user.username }}">
                    <input type="submit" class="btn btn-primary">
                </form>
            </div>
            <div class="col-md-4">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.book.name }}<br/>
                        <span>Price: {{ item.total_price }}</span>
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: Price. {{ cart.get_total_price }}</li>
                </ul>

            </div>
        </div>
    </div>
{% endblock %}

orders/templates/thanks.html
{% extends 'base.html'%}
{% block content %}
<div class="jumbotron text-xs-center" style="text-align: center">
     <h3 class="page-header">Thank You For Shopping With Us</h3>
    <p class="lead"><strong>Your Order has been placed</strong> for further information contact us.</p>
    <hr><p> Your order number is <strong>{{ order.id }}</strong></p>
  <hr>

  <p class="lead">
    <a class="btn btn-primary btn-sm" href="{% url 'home' %}" role="button">Continue to homepage</a>
  </p>
</div>
{% endblock %}